# Generated by Django 2.2.7 on 2019-11-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20180404_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='images',
            new_name='colour',
        ),
    ]
